#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

if [ -n "${DOCKER_LOGIN}" ] && [ -n "${DOCKER_PASSWORD}" ]; then
    if [ -n "${DOCKER_REGISTRY}" ]; then
        echo "Login into Docker Registry ${DOCKER_REGISTRY}..."
        printf '%s' "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin "${DOCKER_REGISTRY}"
    else
        echo "Login into Docker Hub..."
        printf '%s' "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
    fi
fi
