#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

if [ -n "${DOCKER_REGISTRY}" ]; then
    export DOCKER_BASE_IMAGE=${DOCKER_REGISTRY}/${DOCKER_REPO}
else
    export DOCKER_BASE_IMAGE=${DOCKER_REPO}
fi

# Push main tag
docker push "$IMAGE_NAME"

# Push image with tag set to commit hash
docker tag "$IMAGE_NAME" "$DOCKER_BASE_IMAGE:$SOURCE_COMMIT"
docker push "$DOCKER_BASE_IMAGE:$SOURCE_COMMIT"

if [ -n "${DOCKER_LOGIN}" ] && [ -n "${DOCKER_PASSWORD}" ]; then
    if [ -n "${DOCKER_REGISTRY}" ]; then
        echo "Logout of Docker Registry ${DOCKER_REGISTRY}..."
        docker logout "${DOCKER_REGISTRY}"
    else
        echo "Logout of Docker Hub..."
        docker logout
    fi
fi
